include:
  - project: chrisss93/ci
    file: golang/template.gitlab-ci.yml
    ref: fix

integration-tests:
  extends: unit-tests
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    BUILD_TAG: integration
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
